### ISSUE TITLE
Comments on the doc

### ISSUE THREAD

**Issue by acbegen** [Dash-Industry-Forum/Ingest#104] opened 2019-09-27 13:34 UTC
Editorial:
- s/"HTTP 1.1"/"HTTP/1.1"
-s/exising/existing
- processing entity vs. receiving entity, same thing?
-s/mozzilla/mozilla

Others questions/comments:
- Section 4, bullet 3: How frequently? I think, bullet 4 makes bullet 3 redundant.
- Section 4, bullets 18-21: Maybe define new 4xx level error codes?
- Section 5.2, "It is assumed that the ingest source can retrieve these paths and resolve them to IP addresses." Paths do not get resolved to IP addresses.
- Section 5.2, bullet 3: s/at least one or more/at least one
- Bullet 11. seqnums increasing by one? I believe "by one" part is not a requirement for ISO-BMFF.
- Bullet 12. average and maximum bitrates are used somewhere by the receiving entity?
- Section 5.4: How big is the Switching Set ID?
- Section 7.1: I generally think of the output of an encoder as the elementary streams (audio, video, etc.) with certain markings like EBP, not CMAF tracks. I also think it is the packager who converts those elementary streams to CMAF tracks and at the same time outputs the HLS playlist or DASH MPD. Do we need to assume that the encoders will always spit out CMAF tracks? In this picture, it looks like the packager is only producing the playlist and manifest. If that is the only job, I guess we can call it "manifest generator" :)
- Who signals the switching set constraints to the packager?

**Comment by RufaelDev** [comment] 2019-10-03 13:40
Discussed during TF all on october 2nd 2019. 

Section 4, bullet 3: How frequently? I think, bullet 4 makes bullet 3 redundant.
   => make it explicit that DNS should be used, manual configuration of hostnames is possible
Section 4, bullets 18-21: Maybe define new 4xx level error codes?
   => consider as future extension for this protocol, this may help error handling later on as it becomes more relevant in larger scale deployments
Section 5.2, "It is assumed that the ingest source can retrieve these paths and resolve them to IP addresses." Paths do not get resolved to IP addresses.
=> fixed in the text todo change resolve to used
Section 5.2, bullet 3: s/at least one or more/at least one
=> updated text , confirmed to be correct
Bullet 11. seqnums increasing by one? I believe "by one" part is not a requirement for ISO-BMFF.
=> we need to defined this in the spec todo add text 
Bullet 12. average and maximum bitrates are used somewhere by the receiving entity?
=> updated text clarifies this
Section 5.4: How big is the Switching Set ID?
=> it is a string as it is in kind box or in a URI, at smallest it could be a small integer number or a desriptive name of the switching set including its 4cc 
Section 7.1: I generally think of the output of an encoder as the elementary streams (audio, video, etc.) with certain markings like EBP, not CMAF tracks. I also think it is the packager who converts those elementary streams to CMAF tracks and at the same time outputs the HLS playlist or DASH MPD. Do we need to assume that the encoders will always spit out CMAF tracks? In this picture, it looks like the packager is only producing the playlist and manifest. If that is the only job, I guess we can call it "manifest generator" :)
=> discussed, specification chose CMAF/fmp4 approach, lifting on usage of fmp4 + http in DASH and HLS, format does have clear benefits for usage with HTTP and internet based streaming
Who signals the switching set constraints to the packager?
=> these are defined in the CMAF specification itself they do not need to be signalled

**Closed** 2019-10-16 15:32 UTC
Labels: com-rev-public
